// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YouthAtHeart.Models;

namespace YouthAtHeart.Migrations
{
    [DbContext(typeof(YouthAtHeartContext))]
    [Migration("20220118101144_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("YouthAtHeart.Models.HomeInfo", b =>
                {
                    b.Property<string>("homeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("homeImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("homeOverview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("homeId");

                    b.ToTable("HomeInfo");
                });

            modelBuilder.Entity("YouthAtHeart.Models.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("test")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("YouthAtHeart.Models.User", b =>
                {
                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("confirmPass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("YouthAtHeart.Models.WorkshopInfo", b =>
                {
                    b.Property<string>("wsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("endLesDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("firstLesDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("regEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("regStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("teacherId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wsCoverImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wsEnvImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wsExtraInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wsLessonSchedule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wsLocationDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wsLocationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wsMainInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("wsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("wsPrice")
                        .HasColumnType("float");

                    b.Property<double>("wsRating")
                        .HasColumnType("float");

                    b.Property<int>("wsTotalAttendees")
                        .HasColumnType("int");

                    b.Property<string>("wsType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("wsId");

                    b.ToTable("WorkshopInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
